
version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: workly-backend
    ports:
      - "3000:3000"
    # Load environment variables from the root .env file
    env_file:
      - .env
    environment:
      - PORT=3000
    restart: always
    networks:
      - workly-network

  frontend:
    build: 
      context: ./frontend
    container_name: workly-frontend
    ports:
      - "80:5173"
    environment:
      # This URL must be accessible from the user's browser, so use your EC2 Public IP or Domain
      - VITE_API_BASE_URL=http://localhost:3000 
    depends_on:
      - backend
    restart: always
    networks:
      - workly-network

networks:
  workly-network:
    driver: bridge
